services:
  # The production build services uses the dockerfile defined in the root folder.
  angular-prod:
    build:
      context: .
      dockerfile: dockerfile
    image: docker-angular-sample
    ports:
      - "80:8080"

  # The development container is build on the Node iamge with the angular cli installed.
  # Instead of building an image, the folder is mounted as a volume to allow live editing.
  angular-dev:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "80:4200"
    entrypoint: ["sh", "-c", "npm install && npm run start -- --host 0.0.0.0"]
